[workspace]
members = [
  "apps/picsharp-app/src-tauri",
]
resolver = "2"

[workspace.package]
authors = ["JaylenLee"]
license = "AGPL-3.0"
repository = "https://github.com/JaylenLee/PicSharp"
categories = []
edition = "2021"
rust-version = "1.82.0"